import paho.mqtt.client as mqtt
import json
import time
import random
import ssl

# --- 1. Initial Battery State ---
battery_state = {
    "voltage_V": 400.0,
    "current_A": 30.0,
    "cell_temp_C": 25.0,
    "ambient_temp_C": 25.0,
    "soc_percent": 100.0,
    "resistance_ohms": 0.015,
    "capacity_Ah": 100.0
}

# --- Physics Trackers ---
high_current_timer = 0
anomaly_mode = False
anomaly_timer = 0

# --- 2. Setup the MQTT Client ---
client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2, client_id="My_Realistic_Virtual_ESP32")

print("[INFO] Connecting to HiveMQ Cloud...")
try:
    client.username_pw_set("piyush", "12345678")
    client.tls_set(tls_version=ssl.PROTOCOL_TLS)
    # Replace the URL below with your actual Cluster URL!
    client.connect("60b7caa4a2af419a9ac318f17098d27c.s1.eu.hivemq.cloud", 8883, keepalive=60)
except Exception as e:
    print(f"\n[CRITICAL ERROR] Connection failed: {e}")
    exit()

client.loop_start()
print("[STARTED] Simulating realistic EV physics. Press Ctrl+C to stop.\n")

# --- 3. Infinite Data Generation Loop ---
try:
    while True:
        # 1. Ambient Temperature (Drifts naturally between 20°C and 40°C)
        battery_state["ambient_temp_C"] += random.uniform(-0.5, 0.5)
        battery_state["ambient_temp_C"] = max(20.0, min(40.0, battery_state["ambient_temp_C"]))

        # 2. Random Anomaly Trigger (About 1% chance every second to start a battery fire)
        if not anomaly_mode and random.randint(1, 100) == 1:
            anomaly_mode = True
            anomaly_timer = 15  # The fire lasts for 15 seconds
            print("\n🚨 [PHYSICS ENGINE] INJECTING THERMAL RUNAWAY ANOMALY! 🚨\n")
        
        if anomaly_mode:
            anomaly_timer -= 1
            # Battery temperature rapidly shoots up towards 80°C
            battery_state["cell_temp_C"] += random.uniform(3.0, 6.0)
            battery_state["cell_temp_C"] = min(85.0, battery_state["cell_temp_C"])
            battery_state["resistance_ohms"] = 0.035  # Internal resistance degrades/spikes
            
            if anomaly_timer <= 0:
                anomaly_mode = False
                battery_state["resistance_ohms"] = 0.015  # Repair the battery
                print("\n✅ [PHYSICS ENGINE] Anomaly cleared. Initiating cool down...\n")
                
        else:
            # --- NORMAL DRIVING PHYSICS ---
            
            # 3. Current (Amps) - Cruising vs Accelerating
            if high_current_timer > 0:
                # Driver is accelerating heavily
                high_current_timer -= 1
                battery_state["current_A"] = random.uniform(120.0, 160.0)
            else:
                # Normal cruising
                battery_state["current_A"] = random.uniform(20.0, 60.0)
                # 5% chance the driver steps on the gas for 3 to 6 seconds
                if random.random() < 0.05:
                    high_current_timer = random.randint(3, 6)
            
            # 4. Cell Temperature (Heats up under load, cools down to ambient)
            # Target temp is ambient temp + heat generated by the current
            target_temp = battery_state["ambient_temp_C"] + (battery_state["current_A"] * 0.15)
            # Smoothly transition current temp toward target temp
            battery_state["cell_temp_C"] += (target_temp - battery_state["cell_temp_C"]) * 0.1 + random.uniform(-0.2, 0.2)
            # Keep normal temp between 20°C and 60°C max
            battery_state["cell_temp_C"] = max(20.0, min(60.0, battery_state["cell_temp_C"]))

        # 5. Voltage Sag (V = Rated Voltage - (Current * Resistance))
        # As battery drains (SoC drops), the base voltage drops slightly from 400V down to ~350V
        base_voltage = 400.0 - ((100.0 - battery_state["soc_percent"]) * 0.5)
        voltage_sag = battery_state["current_A"] * battery_state["resistance_ohms"]
        battery_state["voltage_V"] = base_voltage - voltage_sag + random.uniform(-0.5, 0.5)

        # 6. State of Charge (Drains accurately based on Current over time)
        drain_rate = (battery_state["current_A"] / 3600.0) / battery_state["capacity_Ah"] * 100.0
        battery_state["soc_percent"] -= drain_rate
        if battery_state["soc_percent"] <= 0:
            battery_state["soc_percent"] = 100.0  # Recharge

        # Build payload
        payload = {
            "timestamp": int(time.time()),
            "voltage_V": round(battery_state["voltage_V"], 2),
            "current_A": round(battery_state["current_A"], 2),
            "cell_temp_C": round(battery_state["cell_temp_C"], 2),
            "ambient_temp_C": round(battery_state["ambient_temp_C"], 2),
            "soc_percent": round(battery_state["soc_percent"], 2),
            "resistance_ohms": round(battery_state["resistance_ohms"], 4),
            "capacity_Ah": battery_state["capacity_Ah"]
        }

        json_payload = json.dumps(payload)
        client.publish("piyush/ev/project/battery1", json_payload)
        
        # Print a clean, readable console output
        status = "🔥 ANOMALY" if anomaly_mode else ("⚡ ACCEL" if high_current_timer > 0 else "🚗 CRUISE")
        print(f"[{status}] Temp: {payload['cell_temp_C']}°C | Curr: {payload['current_A']}A | Volt: {payload['voltage_V']}V")

        time.sleep(1)

except KeyboardInterrupt:
    print("\n[STOPPED] Infinite loop terminated by user.")

finally:
    client.loop_stop()
    client.disconnect()